# Homework 3

##### Deadline for submission of your solutions is **?**.

* Same instructions as in Homework 1 apply here. 
$\newcommand{\dx}{\,\mathrm{d}x}$

In [35]:
# a)-b)
import numpy as np

def midpoint(f,a,b):
    return (f(0.5*(a+b))*(b-a))

def trapezoid(f,a,b):
    return ((f(a)+f(b))*0.5*(b-a))

def simpson(f,a,b):
    m=0.5*(a+b)
    return ((f(a)+4*f(m)+f(b))*(b-a)/6.0)

a=0.0; b=1.0

M=5 # number of monomials to integrate
T=np.zeros((M,3+1))

for i in range(1,M+1):
    f=(lambda x: x**i)
    ex=1.0/(i+1.0)
    T[i-1]=[i,abs(midpoint (f,a,b)-ex),abs(trapezoid(f,a,b)-ex),abs(simpson(f,a,b)-ex)]
print(T)

[[ 1.          0.          0.          0.        ]
 [ 2.          0.08333333  0.16666667  0.        ]
 [ 3.          0.125       0.25        0.        ]
 [ 4.          0.1375      0.3         0.00833333]
 [ 5.          0.13541667  0.33333333  0.02083333]]


In [37]:
# c)
a=0.0; b=1.0

M=5 # number of monomials to integrate

N=4 # number of intervals
for n in [1,2,4]: #range(1,N+1):
    T=np.zeros((M,3+1))
    for i in range(1,M+1):
        Im=0.0; It=0.0; Is=0.0 # restart
        f=(lambda x: x**i)
        ex=1.0/(i+1.0)
        x=np.linspace(a,b,n+1)
        for j in range(0,n):
            Im += midpoint (f,x[j],x[j+1])
            It += trapezoid(f,x[j],x[j+1])
            Is += simpson(f,x[j],x[j+1])
            
        T[i-1]=[i,abs(Im-ex),abs(It-ex),abs(Is-ex)]
    print('Intervals:',n)
    print(T)

Intervals: 1
[[ 1.          0.          0.          0.        ]
 [ 2.          0.08333333  0.16666667  0.        ]
 [ 3.          0.125       0.25        0.        ]
 [ 4.          0.1375      0.3         0.00833333]
 [ 5.          0.13541667  0.33333333  0.02083333]]
Intervals: 2
[[  1.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  2.00000000e+00   2.08333333e-02   4.16666667e-02   5.55111512e-17]
 [  3.00000000e+00   3.12500000e-02   6.25000000e-02   0.00000000e+00]
 [  4.00000000e+00   3.98437500e-02   8.12500000e-02   5.20833333e-04]
 [  5.00000000e+00   4.75260417e-02   9.89583333e-02   1.30208333e-03]]
Intervals: 4
[[  1.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  2.00000000e+00   5.20833333e-03   1.04166667e-02   5.55111512e-17]
 [  3.00000000e+00   7.81250000e-03   1.56250000e-02   0.00000000e+00]
 [  4.00000000e+00   1.03027344e-02   2.07031250e-02   3.25520833e-05]
 [  5.00000000e+00   1.27360026e-02   2.57161458e-02   8.13802083

## Problem 2 (Piecewise Polynomial Approximation)

Let $0 = x_0 < x_1 < x_2 < \ldots < x_N = 1$ be a partition of the interval
$0\leq x\leq 1$ into $N$ subintervals of equal length $h$.  Moreover,
let $\{ \varphi_j\}_{j=0}^N$ be the set of hat basis functions of $V_h$
associated with the $N+1$ nodes $x_j$, $j = 0,1\ldots, N$, such that
\begin{align}
  \varphi_i(x_j) =
  \left \{ 
  \begin{array}{l}
    1, \quad \mbox{if } i = j, \\
    0, \quad \mbox{if } i \neq j.
  \end{array}
  \right .
\end{align}
The explicit expression for a hat function $\varphi_i(x)$ is given by 
\begin{align} 
  \varphi_i(x) =
  \left\{
  \begin{array}{ll}
    (x-x_{i-1})/h, &\mbox{if } x_{i-1} \leq x \leq x_i,\\
    (x_{i+1}-x)/h, & \mbox{if } x_i \leq x \leq x_{i+1},\\
    0, & \mbox{otherwise.} 
  \end{array}
  \right. 
\end{align}

**a)** Write a (short) Python function ${\texttt{hatfun(x,i)}}$, that computes and returns the hat functions $\varphi_i$, $i=0,1,\dots,N$, where ${\texttt{x}}$ is a vector containing the $N+1$ nodal points. Then, plot $\varphi_2$ and $\varphi_N$ in partitions with $N=4,7,10$.

*Hint*: Use the interp1d function from the $\texttt{scipy.interpolate}$ module.

**b**) Write a Python script ${\texttt { plinterp(x,y,xe)}}$, that computes the linear interpolant $\pi f_k\in V_h$, $k=1,2,3$ of 

* $f_1(x)=x\sin (3\pi x)$
* $f_2(x)=2-10x$
* $f_3(x)=x(1-x)$

by using your script ${\texttt {hatfun}}$. Hint: The interpolant is defined 
$$
\pi f(x) = \sum_{i=0}^N f(x_i) \varphi_i(x)
$$
Compute the error in the numerical solution using the $L^2$-norm and present the results in Log-Log plots (error versus $h$) using partitions with $N=2^2,2^3,...,2^6$.  Show that the estimate 
$$
\| f - \pi f \|_{L^2(I)}^2 \leqslant C \sum_{i=1}^N h_i^4 \| f'' \|_{L^2(I_i)}^2
$$
is satisfied for all cases. 

*Hint*: Use the code for the Simpson's below to compute the $L^2$-norm per element.

**c)** Write a new script ${\texttt {AssembleMassMatrix1D(x)}}$ that computes the mass matrix by studying section 1.5.1 in the book and the lecture notes. 

**d)** Write a corresponding function $\texttt{AssembleLoadVector(x,f)}$ which computes 
the load vector for a given function $f$. Make sure that you can easily switch out the quadrature
rule to approximate the integrals $\int_{I} f \varphi_i \dx$

**e)** Compute the $L^2$-projection $P_h f\in V_h$ of $f_1,\,f_2$ and $f_3$ from b) using the
trapezoidal rule to compute load vector. Is the estimate (1.54) in Theorem 1.2 is satisfied for all cases?

**f)** Repeat the numerical study from e), but this time using the Simpson's rule to compute the load vector. 

## Problem (A 1D Finite Element Solver)

**a**) For $u(x) = x + \cos(2\pi x)$, compute a right-hand side $f$ and boundary values $u_0$, $u_1$
such that $u(x)$ solves the two-point boundary value problem
\begin{gather}
-u''= f, \quad 0<x<1, 
\\
u(0)=u_0, \quad u(1)=u_1.
\end{gather}

** b) ** Implement a finite element solver for this two-point boundary problem
as outlined in the lecture notes.
Use uniform meshes with $h=1/2$, $1/4$, $1/16$ and $1/256$. 
Compare the numerical solution $u_h$ with the exact solution $u(x)$ and check that $u_h$ converge to $u$ in the norms

* a) The maximum norm 
* b)
The energy norm  $\|u\|_a^2=\int_0^1 u'(x)^2\,dx$ (Note that the energy norm is problem dependent!)
* c) The $L^2$-norm (compute first $P_h u$ and then $\|P_h u-u_h\|_{L^2(I)}$)


Compute the error in the numerical solution using the norms above and present the results in Log-Log plots (error versus $h$).  

Hint: Show that  $\|u-u_h\|_E^2=\|u'\|^2-\|u_h'\|^2$, where $u$ is the exact solution and $u_h$ is the finite element approximation. 

**c**) (Repeat same with Neuman boundary condition on the left endpoint, check convergence order,
compare with FDM! 



In [1]:
from IPython.core.display import HTML
def css_styling():
    styles = open("../styles/custom.css", "r").read()
    #styles = open("../styles/numericalmoocstyle.css", "r").read()
    return HTML(styles)

# Comment out next line and execute this cell to restore the default notebook style. 
css_styling()